- hosts: ec2
  remote_user: ec2-user
  tasks:
    - name: Add docker repo
      yum_repository:
         name: docker
         description: repo for docker install
         baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/
         gpgcheck: no
         enabled: yes
    - name: Installing Docker ce
      package:
         name: "docker-ce-18.09.1-3.el7.x86_64"
         state: present
    - name: starting services
      service:
         name: 'docker'
         state: started
         enabled: yes
    - name: Installing Docker SDK for python3
      command: pip3 install docker
    - name: Creating folder and copying html file...
      file:
         path: /var/www/html
         state: directory
    - name: Copying html files
      copy:
         src: "new.html"
         dest: "/var/www/html/"


    - name: Creating docker  container using  
      docker_container:
         name: task14
         image: httpd
         state: started
         exposed_ports: "80"
         ports: "8080:80"
         volumes: /var/www/html/:/usr/local/apache2/htdocs/
    - name: Fetching details of docker container
      docker_container_info:
          name: task14
      register: conInfo

    - name: print info
      debug:
              var: conInfo.container.NetworkSettings.IPAddress
    - name: copy
      template:
              dest: /root/ansible-playbooks/dynamic_hosts/docker
              src: ip.txt      

